import { parseSkillDocument } from "../markdown";
import type {
  ContractRule,
  EvidenceRequirement,
  SkillContract,
  SkillPreset,
  WorkflowBlueprint,
  WorkflowStep,
  WorkflowValue,
} from "../types";
import { FLUTTER_DESIGN_SOURCE } from "./flutter-design-source";

const sourceEvidence = (id: string, description: string): EvidenceRequirement => ({
  id,
  type: "source",
  description,
  required: true,
});

const workflowInput = (
  id: string,
  name: string,
  required = true,
  type: WorkflowValue["type"] = "string",
): WorkflowValue => ({ id, name, required, type });

const rule = (
  id: string,
  title: string,
  statement: string,
  kind: ContractRule["kind"],
  strength: ContractRule["strength"] = "required",
  extra: Partial<ContractRule> = {},
): ContractRule => ({
  id,
  title,
  statement,
  kind,
  strength,
  severity: strength === "prohibited" || strength === "required" ? "blocking" : "warning",
  enabled: true,
  ...extra,
});

export function createFlutterDesignPreset(): SkillPreset {
  const contract = createFlutterContract();
  const workflow = createFlutterWorkflow();
  const resources = contract.resources;
  return {
    id: "preset-flutter-app-design",
    name: "Flutter App Design",
    description: "Detailed Material 3, adaptive layout, state, motion, persistence, platform-boundary, and verification contract.",
    // The preset document is the real skill, byte for byte. Contract/workflow
    // projections stay separate and must never inject a second source of truth
    // into SKILL.md.
    document: parseSkillDocument(FLUTTER_DESIGN_SOURCE, { id: "flutter-app-design" }),
    contract,
    workflow,
    resources,
    properties: [
      {
        id: "flutter-design-contract-fields",
        key: "designContract.requiredFields",
        label: "Required source design contract fields",
        value: [
          "routeTask",
          "componentMap",
          "tokenSurfaceMap",
          "stateMatrix",
          "motionEntry",
          "accessibilityChecks",
          "verificationTarget",
        ],
        valueType: "array",
        editable: true,
      },
    ],
  };
}

function createFlutterContract(): SkillContract {
  const rules: ContractRule[] = [
    rule(
      "shared-widget-tree",
      "Shared widget tree",
      "Keep one shared Flutter Material 3 widget tree wherever practical; adapt composition instead of copying pages into platform forks.",
      "platform-boundary",
      "default",
      { platforms: ["Android", "Windows"], requiredEvidence: ["Affected shared source paths"] },
    ),
    rule(
      "material-first",
      "Material or project primitive first",
      "Choose a Material 3 or existing project primitive before creating a custom control.",
      "component-selection",
      "required",
      { requiredEvidence: ["Component map with primitive and justification"] },
    ),
    rule(
      "navigation-semantics",
      "Navigation hierarchy",
      "Use bottom navigation for compact top-level destinations and rail/sidebar/pane shells for wide layouts; use tabs, segmented controls, lists, or detail panes for child switching.",
      "component-selection",
    ),
    rule(
      "single-primary-action",
      "Single high-emphasis action",
      "A route exposes at most one high-emphasis create/add action and only when a real primary task exists.",
      "restriction",
    ),
    rule(
      "input-state-completeness",
      "Input state completeness",
      "Inputs define label, hint, error, disabled, focus, keyboard, validation, and accessibility behavior.",
      "component-selection",
    ),
    rule(
      "modal-completeness",
      "Modal interaction completeness",
      "Dialogs, sheets, and menus define purpose, cancel or escape path, action hierarchy, focus order, scrim or tonal surface, and loading/error behavior.",
      "component-selection",
    ),
    rule(
      "ordinary-rows-not-cards",
      "Ordinary rows are not cards",
      "Lists, settings, profile, directory, history, search, and ordinary content use direct list flow, dividers, state layers, and grouped surfaces rather than one card per row.",
      "restriction",
      "default",
    ),
    rule(
      "semantic-surfaces",
      "Semantic surfaces and tokens",
      "Map page, grouped content, active item, modal, selected item, and raised content to project or Material token roles; do not invent hierarchy with random opacity, blur, or decorative borders.",
      "component-selection",
    ),
    rule(
      "real-icons",
      "Real icon sources",
      "Icons come from Flutter Icon/IconData, project assets, icon fonts, generated icon components, or the current asset pipeline; text, punctuation, words, and emoji are prohibited as icons.",
      "restriction",
      "prohibited",
    ),
    rule(
      "preserve-contracts",
      "Preserve behavior contracts",
      "Preserve navigation meaning, state ownership, data flow, storage, routes, API, Rust bridge, and native capability contracts unless behavior change is explicitly requested.",
      "restriction",
    ),
    rule(
      "page-directory-architecture",
      "Page directory architecture",
      "New or refactored pages live under lib/pages/<page>/, private widgets stay with the page, shared UI uses lib/shared/ or lib/widgets/, and services/models remain outside page files.",
      "restriction",
      "required",
      { pathPatterns: ["lib/pages/<page>/", "lib/shared/", "lib/widgets/"] },
    ),
    rule(
      "stable-breakpoints",
      "Stable responsive breakpoints",
      "Use stable breakpoints or project size-class helpers; viewport-scaled font hacks and negative letter spacing are prohibited.",
      "restriction",
    ),
    rule(
      "custom-control-contract",
      "Custom control contract",
      "A custom control requires a real interaction, layout, animation, or platform need and must preserve semantics, focus, keyboard, touch target, state feedback, reduced motion, and disabled/loading/error states.",
      "component-selection",
      "conditional",
      { requiredEvidence: ["Custom-control need and accessibility/state matrix"] },
    ),
    rule(
      "meaningful-visible-text",
      "Meaningful visible text",
      "Visible text names a real object, action, state, error, navigation target, group, or user decision; tutorial filler, marketing copy, duplicate titles, fake data, metrics, and actions are prohibited.",
      "restriction",
    ),
    rule(
      "durable-data-root",
      "Durable app-data categories",
      "User-owned durable data lives under the platform app-data root in data/<category>/ and uses the shared path helper.",
      "data-path",
      "required",
      { pathPatterns: ["data/settings/", "data/favorites/", "data/history/", "data/search/", "data/conversations/", "data/communities/", "data/provider/"] },
    ),
    rule(
      "cache-outside-data",
      "Cache outside data",
      "Cache, temporary WebView data, thumbnails, transient downloads, and recomputable files use cache/<category>/ outside data/.",
      "data-path",
      "required",
      { pathPatterns: ["cache/webview/", "cache/thumbnails/", "cache/downloads/", "cache/previews/", "cache/tmp/"], requiredEvidence: ["Concrete data and cache paths", "Proof cache path is outside data/"] },
    ),
    rule(
      "credential-boundary",
      "Provider credential boundary",
      "Provider configuration is local app data; credentials never appear in source, task logs, screenshots, public indexes, or non-app-data fallbacks.",
      "data-path",
      "prohibited",
    ),
    rule(
      "meaningful-motion",
      "Meaningful visible-state motion",
      "Attempt meaningful animation for route, modal, list, loading/content, empty/error/retry/success, selection, submit, destructive, hover/focus/press, and progress changes where those states exist.",
      "motion",
      "required",
      { requiredEvidence: ["State-to-motion matrix and shared entry decision"] },
    ),
    rule(
      "shared-motion-entry",
      "Shared motion entry",
      "Search for and reuse shared motion tokens, helpers, wrappers, and theme timing first; repeated motion needs must use or propose one shared entry.",
      "motion",
    ),
    rule(
      "reduced-motion",
      "Reduced-motion alternative",
      "Animation cannot be the only state carrier; color, icon, text, layout, or state-layer cues preserve meaning when motion is reduced.",
      "motion",
    ),
    rule(
      "platform-native-boundary",
      "Platform and native boundary",
      "Do not add parallel native product UI, Rust, native code, or FFI for one-off presentation glue; native checks apply only to shared domain, bindings, artifacts, packaging, or adapters actually touched.",
      "platform-boundary",
      "prohibited",
      { relatedSkills: ["remove-legacy-compat"] },
    ),
    rule(
      "source-audit-before-screenshot",
      "Source audit before screenshot",
      "Prove widget primitives, route hierarchy, token roles, state matrix, shared motion entry, and accessibility semantics before relying on screenshots.",
      "verification",
      "required",
    ),
    rule(
      "utf8-verification",
      "UTF-8 verification",
      "Chinese UI copy, generated resource names, design notes, skill rules, and validation scripts must be checked for mojibake.",
      "verification",
    ),
  ];

  return {
    schemaVersion: 1,
    id: "flutter-app-design-contract",
    name: "Flutter App Design",
    summary: "Material 3 and current project primitives define hierarchy, state, motion, and accessibility; Android and Windows differ only for real target ergonomics.",
    objectives: [
      "Maintain one shared Flutter implementation by default.",
      "Make component, surface, state, motion, accessibility, and platform decisions explicit.",
      "Keep durable data, cache, provider configuration, and native boundaries correct.",
      "Select the smallest effective source and target verification matrix.",
    ],
    triggers: [
      { id: "flutter-ui", label: "Flutter UI", patterns: ["Flutter", "Material 3", "page", "navigation", "settings", "list"] },
      { id: "adaptive", label: "Adaptive layout", patterns: ["Android", "Windows", "responsive", "breakpoint", "resize"] },
      { id: "motion", label: "Visible state change", patterns: ["animation", "motion", "transition", "hover", "focus", "loading"] },
      { id: "native-boundary", label: "Flutter-adjacent native boundary", patterns: ["Rust", "FFI", "native", "binding", "packaging"] },
    ],
    scopeRoutes: [
      { id: "shared", label: "Shared Flutter", platforms: ["Android", "Windows"], default: true, sharedImplementation: true, verificationTargets: ["shared source", "primary affected target"] },
      { id: "android", marker: "(a)", label: "Android only", platforms: ["Android"], verificationTargets: ["affected Android profile"] },
      { id: "windows", marker: "(w)", label: "Windows only", platforms: ["Windows"], verificationTargets: ["affected Windows profile"] },
      { id: "both", marker: "(wa)", label: "Android and Windows", platforms: ["Android", "Windows"], sharedImplementation: true, verificationTargets: ["shared source", "both targets when cross-platform-sensitive"] },
    ],
    rules,
    resources: [
      { id: "skill-source", name: "Flutter app design skill", kind: "file", path: "${CODEX_HOME}/skills/flutter-app-design/SKILL.md", required: true },
      { id: "project-main-index", name: "Project main indexes", kind: "directory", path: "main/", required: false },
      { id: "project-request-rules", name: "Project request rules", kind: "directory", path: "request/", required: false },
    ],
    requiredSkills: ["project-task-intake", "project-workflow-task", "project-quality-gate"],
    qualityGates: [
      {
        id: "source-design-contract",
        name: "Source design contract",
        required: true,
        checks: ["route/task", "component map", "token/surface map", "state matrix", "motion entry", "accessibility", "verification target"],
        failureMessage: "Non-trivial Flutter UI work is missing a source-level design contract.",
      },
      {
        id: "semantic-completion",
        name: "Code semantic completion review",
        required: true,
        checks: ["Material/project primitives", "route hierarchy", "master/detail", "cards/lists", "copy necessity", "motion and reduced motion"],
        evidence: ["Source locations", "Primitive/custom-control rationale", "User-request mapping", "Conclusion"],
      },
      {
        id: "affected-platform-verification",
        name: "Affected-platform verification",
        required: true,
        checks: ["Smallest effective target profile", "Both targets when responsive/assets/state/API/native/packaging is affected", "UTF-8"],
      },
    ],
    completionReportFields: ["scope", "affected surfaces", "source evidence", "motion/shared-entry decision", "verification results or skipped checks", "remaining risk"],
    properties: [
      {
        id: "design-contract-schema",
        key: "flutter.designContract",
        label: "Source-level design contract",
        valueType: "object",
        editable: true,
        value: {
          routeTask: "",
          componentMap: [],
          tokenSurfaceMap: [],
          stateMatrix: [],
          motionEntry: {},
          accessibilityChecks: [],
          verificationTarget: {},
          responsiveProfiles: [],
          dataPathMatrix: [],
          platformImpact: {},
        },
      },
    ],
  };
}

function createFlutterWorkflow(): WorkflowBlueprint {
  const steps: WorkflowStep[] = [
    {
      id: "read-project-rules",
      name: "Read project rules",
      action: "inspect",
      kind: "intake",
      inputs: [workflowInput("workspace", "Workspace path", true, "path")],
      outputs: [workflowInput("rules", "Applicable main/request rules", true, "array")],
      platforms: ["Android", "Windows"],
      dependsOn: [],
      parallel: false,
      success: { status: "rules-loaded", next: ["classify-impact"] },
      failure: { status: "blocked", message: "Relevant project rules could not be established." },
      evidence: [sourceEvidence("rules-index", "Paths of relevant main/ and request/ rules")],
      risk: { level: "low" },
    },
    {
      id: "classify-impact",
      name: "Classify scope and platform impact",
      action: "classify",
      kind: "decision",
      condition: "Parse (a)/(w)/(wa); otherwise default UI/navigation/resource work to shared Flutter.",
      inputs: [workflowInput("request", "User request", true, "markdown"), workflowInput("rules", "Applicable rules", true, "array")],
      outputs: [workflowInput("scope", "Scope route", true, "object"), workflowInput("matrix", "Verification matrix", true, "object")],
      platforms: ["Android", "Windows"],
      dependsOn: ["read-project-rules"],
      parallel: false,
      success: { status: "scope-classified", next: ["define-design-contract"] },
      failure: { status: "blocked", message: "Platform scope remains ambiguous." },
      evidence: [sourceEvidence("scope-decision", "Scope marker, affected surfaces, and cross-target reasons")],
      risk: { level: "medium", description: "Wrong scope can create cross-platform drift." },
    },
    {
      id: "define-design-contract",
      name: "Define source design contract",
      action: "design-contract",
      kind: "implementation",
      inputs: [workflowInput("scope", "Scope route", true, "object"), workflowInput("request", "User request", true, "markdown")],
      outputs: [workflowInput("contract", "Flutter source design contract", true, "object")],
      platforms: ["Android", "Windows"],
      dependsOn: ["classify-impact"],
      parallel: false,
      success: { status: "contract-ready", next: ["select-components", "inspect-motion-and-paths"] },
      failure: { status: "blocked", message: "One or more required design-contract fields are missing." },
      evidence: [sourceEvidence("contract-fields", "All seven required design-contract fields")],
      risk: { level: "medium" },
    },
    {
      id: "select-components",
      name: "Select primitives and hierarchy",
      action: "component-map",
      kind: "implementation",
      inputs: [workflowInput("contract", "Design contract", true, "object")],
      outputs: [workflowInput("component-map", "Component and hierarchy map", true, "array")],
      platforms: ["Android", "Windows"],
      dependsOn: ["define-design-contract"],
      parallel: { enabled: true, group: "design-analysis", maxConcurrency: 2, waitForAll: true },
      success: { status: "components-selected", next: ["implement-shared-ui"] },
      failure: { status: "blocked", message: "Custom control or hierarchy lacks semantic justification." },
      evidence: [sourceEvidence("component-selection", "Material/project primitive selection and custom-control rationale")],
      risk: { level: "medium" },
    },
    {
      id: "inspect-motion-and-paths",
      name: "Inspect shared motion and persistence paths",
      action: "inspect-shared-entries",
      kind: "implementation",
      inputs: [workflowInput("workspace", "Workspace path", true, "path"), workflowInput("contract", "Design contract", true, "object")],
      outputs: [workflowInput("motion-entry", "Shared motion entry", true, "object"), workflowInput("data-paths", "Data/cache path matrix", false, "array")],
      platforms: ["Android", "Windows"],
      dependsOn: ["define-design-contract"],
      parallel: { enabled: true, group: "design-analysis", maxConcurrency: 2, waitForAll: true },
      success: { status: "shared-entries-ready", next: ["implement-shared-ui"] },
      failure: { status: "blocked", message: "Repeated motion or storage logic would create a page-local duplicate." },
      evidence: [sourceEvidence("shared-entry-search", "Paths searched and selected shared motion/path helpers")],
      risk: { level: "medium" },
    },
    {
      id: "implement-shared-ui",
      name: "Implement shared Flutter UI",
      action: "implement",
      kind: "implementation",
      inputs: [workflowInput("component-map", "Component map", true, "array"), workflowInput("motion-entry", "Motion entry", true, "object")],
      outputs: [workflowInput("changed-files", "Changed files", true, "array")],
      platforms: ["Android", "Windows"],
      owner: "main-agent",
      dependsOn: ["select-components", "inspect-motion-and-paths"],
      parallel: false,
      timeout: { seconds: 3600, onTimeout: "escalate" },
      retry: { maxAttempts: 2, retryOn: ["format", "type-check", "focused-test"] },
      success: { status: "implemented", next: ["semantic-source-audit"] },
      failure: { status: "blocked", message: "Implementation does not preserve the recorded behavior contract." },
      evidence: [sourceEvidence("implementation-paths", "Changed source paths and user-request mapping")],
      risk: { level: "medium", mitigations: ["Shared widget tree", "Stable breakpoints", "Existing project primitives"] },
      approval: { required: false },
      destructive: { destructive: false, reversible: true },
    },
    {
      id: "semantic-source-audit",
      name: "Run code semantic completion review",
      action: "source-audit",
      kind: "verification",
      inputs: [workflowInput("changed-files", "Changed files", true, "array"), workflowInput("contract", "Design contract", true, "object")],
      outputs: [workflowInput("semantic-review", "Semantic completion evidence", true, "object")],
      platforms: ["Android", "Windows"],
      owner: "main-agent",
      dependsOn: ["implement-shared-ui"],
      parallel: false,
      success: { status: "semantic-review-pass", next: ["verify-affected-targets"] },
      failure: { status: "repair-required", next: ["implement-shared-ui"], message: "Forward-fix semantic gaps before target verification." },
      evidence: [
        sourceEvidence("primitive-audit", "Material/project primitives and custom-control rationale"),
        sourceEvidence("hierarchy-audit", "Page/route, master/detail, card/list, copy, motion, and reduced-motion conclusions"),
      ],
      risk: { level: "high", description: "Build or screenshots alone cannot prove semantic completion." },
    },
    {
      id: "verify-affected-targets",
      name: "Verify affected target profiles",
      action: "verify",
      kind: "verification",
      condition: "Use the smallest effective profile; verify both targets only for cross-platform-sensitive impact.",
      inputs: [workflowInput("matrix", "Verification matrix", true, "object"), workflowInput("changed-files", "Changed files", true, "array")],
      outputs: [workflowInput("verification-results", "Commands, results, artifacts, and skipped checks", true, "array")],
      platforms: ["Android", "Windows"],
      dependsOn: ["semantic-source-audit"],
      parallel: { enabled: true, group: "target-verification", maxConcurrency: 2, waitForAll: true, failFast: false },
      timeout: { seconds: 1800, onTimeout: "fail" },
      retry: { maxAttempts: 2, delaySeconds: 2, retryOn: ["transient-environment"] },
      success: { status: "verification-pass", next: ["utf8-and-report"] },
      failure: { status: "repair-required", next: ["implement-shared-ui"] },
      evidence: [
        { id: "commands", type: "command", description: "Verification commands and results", required: true },
        { id: "artifacts", type: "artifact", description: "Produced artifact or explicit skipped-check reason", required: true },
      ],
      risk: { level: "medium" },
    },
    {
      id: "utf8-and-report",
      name: "Verify UTF-8 and record completion report",
      action: "complete-report",
      kind: "completion",
      inputs: [workflowInput("semantic-review", "Semantic review", true, "object"), workflowInput("verification-results", "Verification results", true, "array")],
      outputs: [workflowInput("completion-report", "Scope, evidence, skipped checks, and remaining risk", true, "object")],
      platforms: ["Android", "Windows"],
      dependsOn: ["verify-affected-targets"],
      parallel: false,
      success: { status: "completed" },
      failure: { status: "blocked", message: "Completion evidence or UTF-8 validation is incomplete." },
      evidence: [
        { id: "utf8", type: "source", description: "Chinese text and generated names are not mojibake", required: true },
        { id: "report", type: "review", description: "Completion report includes scope, motion decision, verification, skips, and remaining risk", required: true },
      ],
      risk: { level: "low", residualRisk: "Any unavailable target profile is recorded explicitly." },
    },
  ];

  return {
    schemaVersion: 1,
    id: "flutter-app-design-workflow",
    name: "Flutter App Design Workflow",
    description: "From project-rule intake through design contract, shared implementation, semantic audit, affected-target verification, and completion evidence.",
    entryStepIds: ["read-project-rules"],
    terminalStepIds: ["utf8-and-report"],
    states: ["rules-loaded", "scope-classified", "contract-ready", "implemented", "semantic-review-pass", "verification-pass", "completed", "repair-required", "blocked"],
    parameters: [
      workflowInput("request", "User request", true, "markdown"),
      workflowInput("workspace", "Workspace path", true, "path"),
      workflowInput("platform-marker", "Optional a/w/wa marker", false, "string"),
    ],
    steps,
    qualityGates: [
      {
        id: "semantic-gate",
        name: "Flutter semantic completion",
        required: true,
        checks: ["Source locations", "Primitive choice", "Hierarchy", "Cards/lists", "Copy", "Motion/reduced motion"],
      },
      {
        id: "verification-gate",
        name: "Affected target verification",
        required: true,
        checks: ["Required profiles pass", "Skipped checks justified", "UTF-8 passes", "Remaining risk recorded"],
      },
    ],
  };
}
