import { parseSkillDocument } from "../markdown";
import type {
  ContractRule,
  EvidenceRequirement,
  SkillContract,
  SkillPreset,
  WorkflowBlueprint,
  WorkflowStep,
  WorkflowStepKind,
  WorkflowValue,
} from "../types";
import {
  WORKFLOW_TASK_ACTION_NAMES,
  WORKFLOW_TASK_ACTION_RUNTIME,
  WORKFLOW_TASK_PARAMETER_RUNTIME,
  WORKFLOW_TASK_RUNTIME_CATALOG,
} from "./workflow-runtime-catalog";
import {
  WORKFLOW_TASK_SOURCE,
  WORKFLOW_TASK_SOURCE_BYTE_COUNT,
  WORKFLOW_TASK_SOURCE_FENCED_CODE_BLOCK_COUNT,
  WORKFLOW_TASK_SOURCE_H2_COUNT,
  WORKFLOW_TASK_SOURCE_H2_HEADINGS,
  WORKFLOW_TASK_SOURCE_LINE_COUNT,
  WORKFLOW_TASK_SOURCE_SHA256,
} from "./workflow-task-source";

const WORKFLOW_SCRIPT = "D:\\vibecoding\\command\\workflow-task.ps1";

const parameter = (
  id: string,
  name: string,
  required = false,
  type: WorkflowValue["type"] = "string",
): WorkflowValue => {
  const runtime = WORKFLOW_TASK_PARAMETER_RUNTIME.find((entry) => entry.name === id);
  return {
    id,
    name,
    required,
    type,
    multiple: type === "array" || runtime?.powerShellType === "[string[]]",
    defaultValue: runtime?.defaultValue,
    validation: runtime?.runtimeAcceptedValues.length
      ? { enum: [...runtime.runtimeAcceptedValues] }
      : undefined,
    extensions: runtime ? { workflowTaskRuntime: runtime } : undefined,
  };
};

const evidence = (
  id: string,
  description: string,
  type: EvidenceRequirement["type"] = "log",
  required = true,
): EvidenceRequirement => ({ id, description, type, required });

const command = (action: string, argumentsTemplate = "") => ({
  executable: "powershell.exe",
  shell: "powershell.exe",
  command: `powershell.exe -NoProfile -ExecutionPolicy Bypass -File '${WORKFLOW_SCRIPT}' -Action ${action}${argumentsTemplate ? ` ${argumentsTemplate}` : ""}`,
  workingDirectory: "D:\\vibecoding",
});

const actionStep = (
  id: string,
  name: string,
  kind: WorkflowStepKind,
  overrides: Partial<WorkflowStep> = {},
): WorkflowStep => ({
  id,
  name,
  action: id,
  kind,
  inputs: [],
  outputs: [],
  command: command(id),
  platforms: ["Windows"],
  owner: "main-agent",
  dependsOn: [],
  parallel: false,
  risk: { level: "low" },
  destructive: { destructive: false, reversible: true },
  enabled: true,
  extensions: {
    workflowTaskRuntime: WORKFLOW_TASK_ACTION_RUNTIME.find((entry) => entry.action === id) ?? null,
  },
  ...overrides,
});

const rule = (
  id: string,
  title: string,
  statement: string,
  kind: ContractRule["kind"],
  strength: ContractRule["strength"] = "required",
  extra: Partial<ContractRule> = {},
): ContractRule => ({
  id,
  title,
  statement,
  kind,
  strength,
  severity: strength === "required" || strength === "prohibited" ? "blocking" : "warning",
  enabled: true,
  ...extra,
});

export function createWorkflowTaskPreset(): SkillPreset {
  const contract = createWorkflowTaskContract();
  const workflow = createWorkflowTaskBlueprint();
  const resources = contract.resources;
  return {
    id: "preset-project-workflow-task",
    name: "Project Workflow Task",
    description: "Detailed action catalog and lifecycle for workflow-task.ps1 task/log, conflict, collaboration, audit, and cleanup behavior.",
    // The editable document is the byte-faithful skill source. Contract and
    // workflow stay beside it as semantic catalogs; they are not injected into
    // the Markdown as a second source of truth.
    document: parseSkillDocument(WORKFLOW_TASK_SOURCE, { id: "project-workflow-task" }),
    contract,
    workflow,
    resources,
    properties: contract.properties,
    extensions: {
      sourceSnapshot: {
        sha256: WORKFLOW_TASK_SOURCE_SHA256,
        bytes: WORKFLOW_TASK_SOURCE_BYTE_COUNT,
        lines: WORKFLOW_TASK_SOURCE_LINE_COUNT,
        h2Count: WORKFLOW_TASK_SOURCE_H2_COUNT,
        fencedCodeBlockCount: WORKFLOW_TASK_SOURCE_FENCED_CODE_BLOCK_COUNT,
      },
      runtimeCatalog: WORKFLOW_TASK_RUNTIME_CATALOG,
    },
  };
}

function createWorkflowTaskContract(): SkillContract {
  const actionNames = [...WORKFLOW_TASK_ACTION_NAMES];
  const parameterNames = WORKFLOW_TASK_PARAMETER_RUNTIME.map((entry) => entry.name);

  return {
    schemaVersion: 1,
    id: "project-workflow-task-contract",
    name: "Project Workflow Task",
    summary: "Central, revisioned task/log lifecycle with conflict transfer, collaboration, evidence, agent model probes, Final Audit, safe cleanup, and completion archival.",
    objectives: [
      "Keep D:\\vibecoding\\task and D:\\vibecoding\\log as the central source of truth.",
      "Prevent parallel edits when file or directory scopes definitely overlap.",
      "Capture request, plan, scope, evidence, collaboration, audit, validation, and risk without losing metadata.",
      "Block unsupported agent models and incomplete Final Audit before completion.",
    ],
    triggers: [
      { id: "workflow-required", label: "Workflow required", patterns: ["workflow_required: yes", "ordinary modification", "large/high-risk", "complex"] },
      { id: "global-rules", label: "Global rule or skill maintenance", patterns: ["AGENTS.md", "skill", "workflow", "quality gate", "optimal"] },
      { id: "collaboration", label: "Agent collaboration", patterns: ["subtask", "join", "message", "shared context", "spawn", "resume"] },
      { id: "final-audit", label: "Final Audit", patterns: ["Final Audit", "audit-check", "workflow_complete"] },
    ],
    scopeRoutes: [
      { id: "central-workflow", label: "Central workflow", platforms: ["Windows"], default: true, conditions: ["workflow_required: yes"], verificationTargets: ["task JSON", "log JSON", "command result"] },
      { id: "project-commands", label: "Project build/run scripts", platforms: [], conditions: ["Build, run, install, upload, asset, or packaging work"], relatedSkills: ["project-command-ops"] },
      { id: "quality-gate", label: "Verification and Final Audit", platforms: [], conditions: ["Before parent completion"], relatedSkills: ["project-quality-gate"] },
    ],
    rules: [
      rule("central-entry", "Central script only", `Use ${WORKFLOW_SCRIPT}; do not use project command folders as workflow fallbacks.`, "lifecycle"),
      rule("required-start-input", "Required start/subtask input", "Request, Files, and Plan are required and must describe real intended paths and acceptance work.", "lifecycle"),
      rule("flutter-semantic-plan", "Flutter semantic review plan item", "Flutter UI workflow plans include a code semantic completion review covering primitives, routes, hierarchy, cards/lists, copy necessity, and motion.", "evidence"),
      rule("scope-normalization", "Normalized directory scope", "Normalize slashes and trailing separators; a directory overlaps its descendants, while similarly named sibling paths do not.", "conflict"),
      rule("auto-handoff", "Automatic definite-conflict handoff", "A new non-stale task with definite file or directory overlap transfers request, plan, files, and feature to the best matching active task instead of creating a duplicate.", "conflict"),
      rule("conflict-stop", "Stop on confirmed conflict", "After check reports a real non-stale file overlap, stop editing and transfer or explicitly resolve the target task first.", "conflict"),
      rule("cleanup-safety", "Safe cleanup", "Cleanup defaults to dry-run and Apply archives only stale all-items-done or joined tasks; incomplete active tasks are never auto-archived.", "lifecycle"),
      rule("join-before-work", "Join before agent work", "Every child, nested, CLI, or existing agent joins the target task and records its real implementation, verification, or audit role before work.", "collaboration"),
      rule("main-agent-review", "Main-agent review", "The main agent reviews child changes, evidence, conflicts, and remaining risk before merge and completion.", "collaboration"),
      rule("two-model-profiles", "Two agent model profiles", "spark maps to gpt-5.3-codex-spark and professional maps to gpt-5.5; all generated agent commands use high reasoning effort.", "collaboration"),
      rule("model-probe", "Model probe before Apply", "spawn -Apply performs a real model probe, records its result, and fails fast with blocked-model-unavailable when unsupported.", "collaboration"),
      rule("shared-context", "Structured collaboration context", "Use message for progress and blockers and context for indexes, requirements, contracts, decisions, evidence paths, risks, and commands.", "collaboration"),
      rule("parent-context", "Subtask parent snapshot", "Subtask captures parent task ID, file, revision, request, plan, scope, evidence, children, handoffs, participants, context, and recent messages.", "audit"),
      rule("audit-gate", "Final Audit machine gate", "A required Final Audit must be completed and archived, contain item-done evidence and workflow_complete: allow, and reference a fresh matching parentContext.", "audit"),
      rule("optimal-confirmation", "Optimal-solution confirmation", "Global rule, skill, workflow, quality-gate, or optimal-solution work additionally confirms the current solution is optimal or has no high-value improvement.", "audit", "conditional"),
      rule("completion-evidence", "Completion evidence", "Every acceptance item has evidence; verification or skip reasons and remaining risk are recorded before complete.", "completion-report"),
      rule("atomic-revision", "Atomic revisioned storage", "Task JSON updates increment revision, update timestamps, write UTF-8 through a temporary file, and use the workflow mutex.", "lifecycle"),
    ],
    resources: [
      { id: "workflow-script", name: "workflow-task.ps1", kind: "file", path: WORKFLOW_SCRIPT, required: true, platforms: ["Windows"] },
      { id: "active-task-root", name: "Active task root", kind: "directory", path: "D:\\vibecoding\\task", required: true },
      { id: "completed-log-root", name: "Completed log root", kind: "directory", path: "D:\\vibecoding\\log", required: true },
      {
        id: "workflow-skill",
        name: "project-workflow-task skill",
        kind: "file",
        path: "${CODEX_HOME}/skills/project-workflow-task/SKILL.md",
        required: true,
        checksum: `sha256:${WORKFLOW_TASK_SOURCE_SHA256}`,
        content: WORKFLOW_TASK_SOURCE,
      },
      { id: "quality-gate-skill", name: "project-quality-gate skill", kind: "file", path: "${CODEX_HOME}/skills/project-quality-gate/SKILL.md", required: true },
    ],
    requiredSkills: ["project-task-intake", "project-workflow-task", "project-command-ops", "project-quality-gate"],
    qualityGates: [
      {
        id: "acceptance-evidence",
        name: "Acceptance evidence",
        required: true,
        checks: ["All required request/acceptance items complete", "Meaningful item-done notes", "Validation or skip reasons", "Remaining risk"],
      },
      {
        id: "flutter-semantic-evidence",
        name: "Flutter semantic completion evidence",
        required: false,
        condition: "Task changes Flutter UI",
        checks: ["Source paths", "Primitive choice", "User mapping", "Hierarchy", "Cards/lists", "Copy", "Motion/reduced motion"],
      },
      {
        id: "final-audit-gate",
        name: "Final Audit allow",
        required: false,
        condition: "Large/high-risk, complex, explicit audit, or unresolved review risk",
        checks: ["Completed audit child log", "Fresh parentContext", "Item evidence", "workflow_complete: allow", "Optimal confirmation when required"],
      },
    ],
    completionReportFields: ["task status", "log path", "key command results", "Final Audit task/log", "skipped checks", "remaining risk"],
    properties: [
      {
        id: "workflow-actions",
        key: "workflow.actions",
        label: "Action enum",
        value: actionNames,
        valueType: "array",
        editable: true,
        validation: { required: true, minLength: 19 },
      },
      {
        id: "workflow-parameters",
        key: "workflow.parameters",
        label: "Script parameter catalog",
        value: parameterNames,
        valueType: "array",
        editable: true,
        validation: { required: true, minLength: 33 },
      },
      {
        id: "workflow-runtime-actions",
        key: "workflow.runtimeActions",
        label: "PowerShell action runtime catalog",
        description: "All 19 dispatch handlers with exact parameter applicability, fallbacks, outputs, errors, state transitions, and side effects.",
        value: WORKFLOW_TASK_ACTION_RUNTIME,
        valueType: "array",
        editable: true,
        validation: { required: true, minLength: 19, maxLength: 19 },
      },
      {
        id: "workflow-runtime-parameters",
        key: "workflow.runtimeParameters",
        label: "PowerShell parameter runtime catalog",
        description: "All 33 parameters with aliases, declared type/default, ValidateSet/runtime legal values, applicable actions, and fallback/output/error semantics.",
        value: WORKFLOW_TASK_PARAMETER_RUNTIME,
        valueType: "array",
        editable: true,
        validation: { required: true, minLength: 33, maxLength: 33 },
      },
      {
        id: "workflow-source-snapshot",
        key: "workflow.sourceSnapshot",
        label: "Exact workflow skill snapshot",
        valueType: "object",
        editable: false,
        value: {
          sha256: WORKFLOW_TASK_SOURCE_SHA256,
          bytes: WORKFLOW_TASK_SOURCE_BYTE_COUNT,
          lines: WORKFLOW_TASK_SOURCE_LINE_COUNT,
          h2Count: WORKFLOW_TASK_SOURCE_H2_COUNT,
          h2Headings: WORKFLOW_TASK_SOURCE_H2_HEADINGS,
          fencedCodeBlockCount: WORKFLOW_TASK_SOURCE_FENCED_CODE_BLOCK_COUNT,
        },
      },
      {
        id: "task-record-schema",
        key: "workflow.taskRecord",
        label: "Task record fields",
        valueType: "object",
        editable: true,
        value: {
          activeRoot: ["taskId", "parentTaskId", "createdAt", "updatedAt", "rawRequest", "plan", "scope", "revision", "doneItems", "itemNotes", "childTasks", "handoffs", "participants", "messages", "sharedContext", "spawnedAgents", "collaborationPolicy", "parentContext", "status"],
          completedLogOnly: ["completedAt", "modifiedFiles", "validation", "auditDecision", "risk"],
          scope: ["projects", "files", "feature", "platforms"],
          itemNote: ["item", "note", "at"],
          childTask: ["taskId", "status", "scope", "parentContextCaptured", "parentRevisionCaptured", "parentContextCapturedAt", "updatedAt"],
          handoff: ["fromTaskId", "request", "plan", "at", "type"],
          participant: ["agent", "role", "agentType", "model", "modelNote", "sourceTaskId", "joinedAt", "rule"],
          message: ["id", "kind", "from", "to", "text", "at"],
          sharedContext: ["key", "value", "updatedBy", "updatedAt"],
          spawnedAgent: ["id", "agent", "agentType", "role", "model", "modelNote", "command", "status", "createdAt", "rule", "modelProbe", "processId"],
          collaborationPolicy: ["discoverable", "joinable", "mainAgentReviewRequired", "recommendedAgentCreation", "subagentWorkRule", "communicationRule"],
          parentContext: ["contextVersion", "capturedAt", "source", "taskId", "taskFile", "parentRevision", "createdAt", "updatedAt", "status", "rawRequest", "plan", "scope", "doneItems", "itemNotes", "childTasks", "handoffs", "participants", "sharedContext", "messages"],
          modelProbe: ["Model", "Available", "ExitCode", "Reason", "StartedAt", "FinishedAt", "OutputDir", "Expected"],
        },
      },
      {
        id: "workflow-statuses",
        key: "workflow.statuses",
        label: "Lifecycle statuses",
        valueType: "object",
        editable: true,
        value: {
          task: ["active", "all-items-done", "joined"],
          transient: ["proposed"],
          log: ["completed"],
          child: ["active", "completed"],
          agent: ["planned", "started", "blocked-model-unavailable"],
          audit: ["allow", "block"],
        },
      },
      {
        id: "conflict-score",
        key: "workflow.conflictScoreWeights",
        label: "Conflict score weights",
        valueType: "object",
        editable: true,
        value: { project: 80, file: 120, feature: 50, platform: 20, staleMinutesDefault: 120 },
      },
      {
        id: "audit-gate-schema",
        key: "workflow.auditGate",
        label: "Audit gate fields",
        valueType: "object",
        editable: true,
        value: {
          fields: ["Decision", "ParentTaskId", "AuditTaskId", "AuditLog", "NeedsOptimal", "WorkflowComplete", "OptimalConfirmed", "ParentContextFresh", "ParentContextReason", "ParentRevision", "CapturedRevision", "Reasons"],
          requiredAllowEvidence: ["completed audit log", "matching fresh parentContext", "workflow_complete allow", "item-done note", "optimal confirmation when needed"],
          exactSemantics: {
            workflowCompletePattern: "workflow_complete\\s*:\\s*(allow|block)",
            optimalConfirmationPhrases: ["当前已是最优解", "无高价值改进项", "不建议继续拆分"],
            finalAuditDiscovery: "child/log scope.feature normalized contains final-audit",
            allowedParentRevisionDelta: { activeAudit: 1, completedAudit: 2 },
          },
        },
      },
    ],
    extensions: {
      runtimeCatalog: WORKFLOW_TASK_RUNTIME_CATALOG,
      sourceSnapshotSha256: WORKFLOW_TASK_SOURCE_SHA256,
    },
  };
}

function createWorkflowTaskBlueprint(): WorkflowBlueprint {
  const steps: WorkflowStep[] = [
    actionStep("start", "Start task", "intake", {
      description: "Create an active task after required-input and recent conflict checks; definite overlap auto-hands off instead.",
      inputs: [parameter("Request", "Request", true, "markdown"), parameter("Files", "Files/directories", true, "array"), parameter("Plan", "Plan/acceptance items", true, "markdown"), parameter("Feature", "Feature"), parameter("Platforms", "Explicit platforms", false, "array")],
      outputs: [parameter("TaskId", "Created task ID", true), parameter("TaskPath", "Task JSON path", true, "path"), parameter("ConflictCandidates", "Conflict candidates", true, "array")],
      command: command("start", "-Request <text> -Files <paths> -Plan <text> -NoPrompt"),
      success: { status: "active", next: ["check", "summary"] },
      failure: { status: "blocked", message: "Missing required input or workflow storage failure." },
      evidence: [evidence("task-path", "Created task path or automatic handoff target", "path")],
      risk: { level: "medium", description: "A wrong scope can hide a real edit conflict.", mitigations: ["Normalize paths", "Check recent active tasks"] },
    }),
    actionStep("check", "Check conflict candidates", "decision", {
      inputs: [parameter("TaskId", "Task ID", true)],
      outputs: [parameter("Candidates", "Ranked overlap candidates", true, "array")],
      command: command("check", "-TaskId <task-id>"),
      dependsOn: ["start"],
      success: { status: "checked", next: ["conflict", "append", "subtask", "join"] },
      failure: { status: "blocked", message: "Task is invalid or cannot be resolved." },
      evidence: [evidence("overlap", "Project/file/feature/platform overlap and recommendation")],
    }),
    actionStep("conflict", "Transfer confirmed conflict", "handoff", {
      condition: "check reports a definite non-stale file or directory overlap",
      inputs: [parameter("TaskId", "Target task ID", true), parameter("FromTaskId", "Source task ID", true), parameter("Request", "Transferred request", true, "markdown"), parameter("Plan", "Transferred plan", true, "markdown"), parameter("Files", "Transferred scope", false, "array")],
      outputs: [parameter("Handoff", "Handoff record", true, "object")],
      command: command("conflict", "-TaskId <target> -FromTaskId <source> -Request <text> -Plan <text> -Files <paths>"),
      dependsOn: ["check"],
      success: { status: "handed-off", next: ["summary"] },
      failure: { status: "blocked", message: "Do not continue parallel editing when transfer fails." },
      evidence: [evidence("handoff-record", "Target request/plan/scope and handoffs were updated", "source")],
      risk: { level: "high", description: "Continuing after a confirmed overlap can overwrite concurrent user work." },
    }),
    actionStep("append", "Append request and plan", "action", {
      inputs: [parameter("TaskId", "Task ID", true), parameter("Request", "New request", true, "markdown"), parameter("Plan", "New plan", true, "markdown"), parameter("Files", "Additional files", false, "array"), parameter("Feature", "Additional feature"), parameter("Platforms", "Additional platforms", false, "array")],
      outputs: [parameter("Revision", "Updated revision", true, "number")],
      command: command("append", "-TaskId <task-id> -Request <text> -Plan <text>"),
      dependsOn: ["check"],
      success: { status: "active", next: ["item-done"] },
      failure: { status: "blocked" },
      evidence: [evidence("append", "Request, plan, merged scope, timestamp, and revision", "source")],
    }),
    actionStep("subtask", "Create child task", "collaboration", {
      inputs: [parameter("ParentTaskId", "Parent task ID", true), parameter("Request", "Child request", true, "markdown"), parameter("Files", "Child files", true, "array"), parameter("Plan", "Child plan", true, "markdown"), parameter("Feature", "Child feature"), parameter("Platforms", "Child platforms", false, "array")],
      outputs: [parameter("TaskId", "Child task ID", true), parameter("ParentContext", "Captured parent context", true, "object")],
      command: command("subtask", "-ParentTaskId <parent> -Request <text> -Files <paths> -Plan <text>"),
      dependsOn: ["check"],
      success: { status: "active", next: ["join", "item-done"] },
      failure: { status: "blocked" },
      evidence: [evidence("parent-context", "Child parentContext and parent childTasks entry", "source")],
    }),
    actionStep("join", "Join or merge task", "collaboration", {
      inputs: [parameter("TaskId", "Target task ID", true), parameter("FromTaskId", "Optional source task ID"), parameter("AgentName", "Agent name"), parameter("AgentRole", "Agent role"), parameter("AgentType", "spark or professional"), parameter("Model", "Model override")],
      outputs: [parameter("Participant", "Participant record", true, "object"), parameter("Handoff", "Optional join-merge handoff", false, "object")],
      command: command("join", "-TaskId <target> -AgentName <name> -AgentRole <role> -AgentType <spark|professional>"),
      agentType: "spark|professional",
      model: "gpt-5.3-codex-spark|gpt-5.5",
      dependsOn: ["check"],
      success: { status: "joined", next: ["message", "context", "spawn", "item-done"] },
      failure: { status: "blocked", message: "Agent must not begin work before join succeeds." },
      evidence: [evidence("participant", "Participant and join message; source marked joined when merged", "source")],
    }),
    actionStep("message", "Write collaboration message", "collaboration", {
      inputs: [parameter("TaskId", "Task ID", true), parameter("AgentName", "Sender"), parameter("ToAgent", "Recipient"), parameter("Note", "Message", false, "markdown")],
      outputs: [parameter("Message", "Timestamped message record", true, "object")],
      command: command("message", "-TaskId <task-id> -AgentName <name> -ToAgent <agent|all> -Note <text>"),
      dependsOn: ["join"],
      parallel: { enabled: true, group: "collaboration", maxConcurrency: 4, waitForAll: false },
      success: { status: "message-written" },
      failure: { status: "blocked" },
      evidence: [evidence("message", "Message ID, kind, sender, recipient, text, and timestamp", "source")],
    }),
    actionStep("context", "Update shared context", "collaboration", {
      inputs: [parameter("TaskId", "Task ID", true), parameter("ContextKey", "Context key", true), parameter("ContextValue", "Context value", true, "markdown"), parameter("AgentName", "Updating agent")],
      outputs: [parameter("SharedContext", "Upserted context record", true, "object")],
      command: command("context", "-TaskId <task-id> -ContextKey <key> -ContextValue <value>"),
      dependsOn: ["join"],
      parallel: { enabled: true, group: "collaboration", maxConcurrency: 4, waitForAll: false },
      success: { status: "context-written" },
      failure: { status: "blocked" },
      evidence: [evidence("context-record", "Context key, value, updatedBy, updatedAt, and context message", "source")],
    }),
    actionStep("spawn", "Prepare or start Codex agent", "collaboration", {
      inputs: [parameter("TaskId", "Task ID", true), parameter("AgentName", "Agent name"), parameter("AgentRole", "Agent role"), parameter("AgentType", "spark or professional"), parameter("Model", "Model override"), parameter("AgentPrompt", "Additional prompt", false, "markdown"), parameter("Apply", "Actually start agent", false, "boolean"), parameter("TimeoutSeconds", "Model probe timeout", false, "number")],
      outputs: [parameter("SpawnedAgent", "Spawn record", true, "object"), parameter("Command", "Codex CLI command", true, "string"), parameter("ModelProbe", "Probe result when Apply", false, "object")],
      command: command("spawn", "-TaskId <task-id> -AgentName <name> -AgentType <spark|professional> [-Apply]"),
      agentType: "spark|professional",
      model: "gpt-5.3-codex-spark|gpt-5.5",
      dependsOn: ["join"],
      success: { status: "planned-or-started", next: ["message", "context"] },
      failure: { status: "blocked-model-unavailable", message: "Fail fast and record probe output when the selected model is unavailable." },
      evidence: [evidence("spawn-record", "Model profile, high-reasoning command, status, probe, and process ID when started", "source")],
      risk: { level: "medium", mitigations: ["Dry-run by default", "Real model probe before Apply", "New agent joins first"] },
      approval: { required: true, before: "apply", reason: "Apply launches a background Codex CLI process." },
    }),
    actionStep("resume-agent", "Prepare agent resume command", "collaboration", {
      inputs: [parameter("TaskId", "Task ID", true), parameter("SessionId", "Codex session ID"), parameter("AgentType", "spark or professional"), parameter("Model", "Model override"), parameter("AgentPrompt", "Continuation prompt", false, "markdown")],
      outputs: [parameter("Command", "Resume command", true), parameter("Message", "Recorded resume message", true, "object")],
      command: command("resume-agent", "-TaskId <task-id> -SessionId <session-id> -AgentType <spark|professional>"),
      agentType: "spark|professional",
      model: "gpt-5.3-codex-spark|gpt-5.5",
      dependsOn: ["join"],
      success: { status: "resume-command-prepared" },
      failure: { status: "blocked" },
      evidence: [evidence("resume-message", "Session, model profile, and reminder to read summary/messages/sharedContext", "source")],
    }),
    actionStep("model-test", "Probe supported agent models", "verification", {
      inputs: [parameter("TaskId", "Optional task ID"), parameter("TimeoutSeconds", "Probe timeout", false, "number")],
      outputs: [parameter("Results", "Spark and professional probe results", true, "array")],
      command: command("model-test", "[-TaskId <task-id>] -TimeoutSeconds <seconds>"),
      agentType: "spark|professional",
      model: "gpt-5.3-codex-spark|gpt-5.5",
      success: { status: "model-test-complete" },
      failure: { status: "blocked", message: "Only task/context persistence failures abort this action; unavailable probes remain successful result rows." },
      evidence: [evidence("model-results", "Availability, reason, exit code, output directory, and testedAt for both profiles")],
    }),
    actionStep("item-done", "Record completed item evidence", "verification", {
      inputs: [parameter("TaskId", "Task ID", true), parameter("Item", "Request/acceptance item number", true, "number"), parameter("Note", "Optional evidence note", false, "markdown")],
      outputs: [parameter("Status", "active or all-items-done", true), parameter("ItemNote", "Evidence record", true, "object")],
      command: command("item-done", "-TaskId <task-id> -Item <number> -Note <evidence>"),
      success: { status: "active-or-all-items-done", next: ["audit-check", "complete"] },
      failure: { status: "blocked", message: "The request list is empty, the item index is invalid, or storage fails; an empty Note does not fail the script." },
      evidence: [evidence("item-note", "Command/result/path evidence associated with the completed item", "source")],
    }),
    actionStep("audit-check", "Run Final Audit machine gate", "audit", {
      condition: "Final Audit is required or an audit task ID is supplied",
      inputs: [parameter("ParentTaskId", "Parent task ID", true), parameter("FromTaskId", "Audit task ID")],
      outputs: [parameter("Decision", "allow or block", true), parameter("Reasons", "Block reasons", true, "array"), parameter("AuditLog", "Archived audit log path", false, "path")],
      command: command("audit-check", "-ParentTaskId <parent> -FromTaskId <audit-task>"),
      dependsOn: ["item-done"],
      success: { status: "allow", next: ["complete"] },
      failure: { status: "block", message: "Repair evidence or recreate a fresh audit child before completion." },
      evidence: [evidence("audit-result", "Completed audit log, fresh parentContext, allow decision, item evidence, and optimal confirmation when required")],
      risk: { level: "high", description: "A stale or evidence-free audit cannot authorize parent completion." },
    }),
    actionStep("complete", "Archive completed task", "completion", {
      condition: "Quality gate passed; all required evidence, validation, skipped checks, and remaining risk are recorded.",
      inputs: [parameter("TaskId", "Task ID", true), parameter("TaskName", "Log name"), parameter("Validation", "Verification and audit evidence", false, "markdown"), parameter("Risk", "Remaining risk", false, "markdown")],
      outputs: [parameter("LogPath", "Completed log path", true, "path")],
      command: command("complete", "-TaskId <task-id> -Validation <evidence> -Risk <risk>"),
      dependsOn: ["item-done"],
      success: { status: "completed" },
      failure: { status: "blocked", message: "Task resolution or log/write/delete operations failed; the script itself does not reject empty Validation or Risk." },
      evidence: [evidence("completed-log", "UTF-8 completed log with request, plan, scope, evidence, collaboration, validation, audit decision, and risk", "path")],
      risk: { level: "medium", mitigations: ["Write log before removing active task", "Update parent child status"] },
      destructive: { destructive: true, reversible: true, exactTargetRequired: true, confirmationRequired: false, rollback: "Restore the archived log as an active task only through an explicit recovery workflow." },
    }),
    actionStep("summary", "Show active overview or task detail", "action", {
      inputs: [parameter("TaskId", "Optional task ID"), parameter("Limit", "Visible result limit", false, "number"), parameter("IncludeStale", "Include stale tasks", false, "boolean"), parameter("StaleOnly", "Only stale tasks", false, "boolean")],
      outputs: [parameter("Summary", "Overview or detailed task summary", true, "object")],
      command: command("summary", "[-TaskId <task-id>]"),
      parallel: true,
      success: { status: "read" },
      failure: { status: "not-found" },
      evidence: [evidence("summary-output", "Status, progress, scope, children, handoffs, participants, context, messages, and spawned agents", "log", false)],
    }),
    actionStep("status", "Show task status", "action", {
      description: "Alias of summary.",
      inputs: [parameter("TaskId", "Optional task ID")],
      outputs: [parameter("Summary", "Task summary", true, "object")],
      command: command("status", "[-TaskId <task-id>]"),
      parallel: true,
      success: { status: "read" },
      failure: { status: "not-found" },
    }),
    actionStep("cleanup", "Preview or archive safe stale tasks", "cleanup", {
      inputs: [parameter("StaleMinutes", "Stale threshold", false, "number"), parameter("Limit", "Candidate limit", false, "number"), parameter("Apply", "Archive candidates", false, "boolean")],
      outputs: [parameter("Candidates", "Safe cleanup candidates", true, "array"), parameter("Logs", "Archived logs when applied", false, "array")],
      command: command("cleanup", "-StaleMinutes <minutes> [-Apply]"),
      condition: "Only stale all-items-done or joined tasks qualify; active incomplete tasks never qualify.",
      success: { status: "dry-run-or-archived" },
      failure: { status: "blocked" },
      evidence: [evidence("cleanup-candidates", "Task ID, age, status, reason, Apply flag, and archived log paths")],
      risk: { level: "medium", mitigations: ["Dry-run by default", "Safe status allowlist"] },
      approval: { required: true, before: "apply", reason: "Apply archives and removes active task files." },
      destructive: { destructive: true, reversible: true, exactTargetRequired: true, confirmationRequired: true, backupRequired: false },
    }),
    actionStep("self-test", "Run isolated workflow smoke test", "verification", {
      inputs: [parameter("WorkflowRoot", "Optional isolated workflow root", false, "path")],
      outputs: [parameter("SelfTestDir", "Self-test evidence directory", true, "path"), parameter("Result", "Pass/fail result", true)],
      command: command("self-test", "[-WorkflowRoot <temporary-root>]"),
      condition: "Run after workflow-task.ps1 changes; prefer an isolated D-drive WorkflowRoot.",
      success: { status: "pass" },
      failure: { status: "block", message: "Repair the central script and rerun." },
      evidence: [evidence("self-test", "Conflict handoff, join, message/context, spawn command, resume, cleanup, missing-evidence block, and audit allow cases", "test")],
      timeout: { seconds: 300, onTimeout: "fail" },
      retry: { maxAttempts: 1 },
    }),
    actionStep("help", "Show workflow help", "action", {
      outputs: [parameter("Help", "Action and option guide", true, "markdown")],
      command: command("help"),
      parallel: true,
      success: { status: "read" },
      failure: { status: "blocked" },
    }),
  ];

  return {
    schemaVersion: 1,
    id: "project-workflow-task-blueprint",
    name: "Project Workflow Task Blueprint",
    description: "Typed catalog of all 19 workflow-task actions and the guarded task lifecycle from intake through conflict handling, collaboration, evidence, audit, cleanup, and archival.",
    entryStepIds: ["start", "summary", "status", "cleanup", "model-test", "self-test", "help"],
    terminalStepIds: ["complete", "conflict", "cleanup", "model-test", "self-test", "help"],
    states: ["proposed", "active", "all-items-done", "joined", "completed", "blocked", "allow"],
    parameters: [
      parameter("Action", "Action"),
      parameter("TaskId", "Task ID"),
      parameter("Request", "User request", false, "markdown"),
      parameter("Plan", "Plan", false, "markdown"),
      parameter("TaskName", "Task/log name"),
      parameter("ParentTaskId", "Parent task ID"),
      parameter("FromTaskId", "Source or audit task ID"),
      parameter("Projects", "Projects", false, "array"),
      parameter("Files", "Files/directories", false, "array"),
      parameter("Feature", "Feature"),
      parameter("Platforms", "Platforms", false, "array"),
      parameter("Validation", "Validation", false, "markdown"),
      parameter("Risk", "Risk", false, "markdown"),
      parameter("Item", "Item number", false, "number"),
      parameter("Note", "Evidence/message note", false, "markdown"),
      parameter("NoPrompt", "Disable prompt", false, "boolean"),
      parameter("Prompt", "Enable interactive prompt", false, "boolean"),
      parameter("IncludeStale", "Include stale", false, "boolean"),
      parameter("StaleOnly", "Only stale", false, "boolean"),
      parameter("Limit", "Display limit", false, "number"),
      parameter("StaleMinutes", "Stale threshold", false, "number"),
      parameter("WorkflowRoot", "Workflow root override", false, "path"),
      parameter("AgentName", "Agent name"),
      parameter("AgentRole", "Agent role"),
      parameter("ToAgent", "Message recipient"),
      parameter("ContextKey", "Context key"),
      parameter("ContextValue", "Context value", false, "markdown"),
      parameter("Model", "Model override"),
      parameter("AgentType", "Agent profile"),
      parameter("SessionId", "Codex session ID"),
      parameter("AgentPrompt", "Agent prompt", false, "markdown"),
      parameter("Apply", "Apply side effect", false, "boolean"),
      parameter("TimeoutSeconds", "Probe timeout", false, "number"),
    ],
    steps,
    qualityGates: [
      {
        id: "workflow-completion",
        name: "Workflow completion",
        required: true,
        checks: ["Acceptance evidence", "Verification or skip reasons", "Remaining risk", "Flutter semantic evidence when applicable", "Final Audit allow when required"],
      },
    ],
    resources: [
      { id: "script", name: "workflow-task.ps1", kind: "file", path: WORKFLOW_SCRIPT, required: true },
      { id: "tasks", name: "Active task JSON", kind: "directory", path: "D:\\vibecoding\\task", required: true },
      { id: "logs", name: "Completed logs", kind: "directory", path: "D:\\vibecoding\\log", required: true },
    ],
    properties: [
      {
        id: "mutex",
        key: "workflow.mutex",
        label: "Concurrency lock",
        value: "Local\\ProjectWorkflowTaskJsonLock",
        valueType: "string",
        editable: true,
      },
      {
        id: "write-mode",
        key: "workflow.storageWriteMode",
        label: "Storage write mode",
        value: { encoding: "UTF-8", atomicReplace: true, revisioned: true, mutexTimeoutSeconds: 60 },
        valueType: "object",
        editable: true,
      },
    ],
    extensions: {
      runtimeCatalog: WORKFLOW_TASK_RUNTIME_CATALOG,
      sourceSnapshot: {
        sha256: WORKFLOW_TASK_SOURCE_SHA256,
        bytes: WORKFLOW_TASK_SOURCE_BYTE_COUNT,
        lines: WORKFLOW_TASK_SOURCE_LINE_COUNT,
        h2Count: WORKFLOW_TASK_SOURCE_H2_COUNT,
        fencedCodeBlockCount: WORKFLOW_TASK_SOURCE_FENCED_CODE_BLOCK_COUNT,
      },
    },
  };
}
